services:
  reactor-client:
    image: reactor-client
    command: reactor-server
  reactor-server:
    deploy:
      endpoint_mode: dnsrr
      replicas: 4
    image: reactor-server
  rx-client:
    image: rx-client
    command: rx-server
  rx-server:
    deploy:
      endpoint_mode: dnsrr
      replicas: 4
    image: rx-server
version: '3.2'
