apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reactor-server
    version: 1
  name: reactor-server
spec:
  selector:
    matchLabels:
      app: reactor-server
  replicas: 4
  template:
    metadata:
      labels:
        app: reactor-server
    spec:
      containers:
        - args:
            - ping.ReactorServer
          image: grpc-load-balancing-demo
          imagePullPolicy: Never
          name: reactor-server
          ports:
            - containerPort: 50505
---
apiVersion: v1
kind: Service
metadata:
  name: reactor-server
spec:
  clusterIP: None
  ports:
    - name: grpc
      port: 50505
  selector:
    app: reactor-server
