apiVersion: apps/v1
kind: Deployment
metadata:
  name: rx-client
spec:
  selector:
    matchLabels:
      app: rx-client
  template:
    metadata:
      labels:
        app: rx-client
    spec:
      containers:
        - args:
            - ping.RxClient
            - $(NODE_NAME):4140
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: grpc-load-balancing-demo
          imagePullPolicy: Never
          name: rx-client
